##########datasource
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/farm?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}
spring.datasource.username=${DATABASE_USERNAME:zhangkun}
spring.datasource.password=${DATABASE_PASSWORD:138992}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
##########mybatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.farm.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
##########log
logging.level.root=warn
logging.level.com.farm=debug
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %C.%M[%line] - %msg%n
##########jackson
spring.jackson.default-property-inclusion=non_null
##########crypto
my.secretkey=KD5F7G8RJ6Z7
my.salt=a48df23c4b8a
